name: release

on:
  # schedule:
  #   - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      repo:
        description: "Nimbus repository to build"
        required: true
        type: string
        default: "status-im/nimbus-eth2"
      ref:
        description: "Nimbus repository reference to build"
        required: true
        type: string
      tag:
        description: "Tag to use for the release"
        required: false
        type: string
      arch:
        description: "Architecture to build for"
        required: true
        type: choice
        default: "linux/amd64"
        options:
          - linux/amd64
          - linux/arm64

jobs:
  build:
    # The binary needs to be built in the same Docker image used as base
    # in the final image in order to link the right dependencies.
    container: debian:bullseye-slim
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    env:
      VERSION: ${{ inputs.ref }}

    steps:
      - name: Install dependencies in build container
        run: |
          apt update
          apt install -y git build-essential

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ env.VERSION }}
          submodules: recursive

      - name: Build binaries
        run: |
          # Change repo owner, as it otherwise causes git safe.directory issues for some reason
          chown -R root: .

          # Configuration
          DEPENDENCIES=${{ fromJson('{ "linux/arm64": "gcc-aarch64-linux-gnu" }')[inputs.arch] }}
          NIMFLAGS_COMMON="-d:const_preset=gnosis -d:disableMarchNative --gcc.options.debug:'-g1' --clang.options.debug:'-gline-tables-only'"
          BINARIES="nimbus_beacon_node"

          # Install cross-compile dependencies
          [ ! -z $DEPENDENCIES ] && apt install -y $DEPENDENCIES

          # Build Nim
          make update -j$(nproc)

          # Build the client for the given platform
          if [[ "${{ inputs.arch }}" == "linux/amd64" ]]; then
            make \
              LOG_LEVEL=TRACE \
              NIMFLAGS="${NIMFLAGS_COMMON}" \
              PARTIAL_STATIC_LINKING=1 \
              QUICK_AND_DIRTY_COMPILER=1 \
              ${BINARIES}
          elif [[ "${{ inputs.arch }}" == "linux/arm64" ]]; then
            CC="aarch64-linux-gnu-gcc"
            
            make \
              -j$(nproc) \
              USE_LIBBACKTRACE=0 \
              QUICK_AND_DIRTY_COMPILER=1 \
              deps-common build/generate_makefile

            make \
              LOG_LEVEL="TRACE" \
              CC="${CC}" \
              NIMFLAGS="${NIMFLAGS_COMMON} --cpu:arm64 --gcc.exe=${CC} --gcc.linkerexe=${CC}" \
              PARTIAL_STATIC_LINKING=1 \
              ${BINARIES}
          else
            echo "Unsupported platform"
            exit 1
          fi

      - name: String manipulation
        id: artifact
        run: |
          NAME=${{ inputs.arch }}
          echo "name=${NAME//\//-}" >> $GITHUB_OUTPUT

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: ./build

  package:
    runs-on: ubuntu-latest

    if: always() && needs.build.result == 'success'
    needs: [build]
    env:
      VERSION: ${{ inputs.tag || inputs.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern=v{{version}},value=${{ env.VERSION }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ env.VERSION }}
            type=semver,pattern=v{{major}},value=${{ env.VERSION }}
            type=raw,value=${{ env.VERSION }},enable=${{ github.event_name != 'schedule' }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ fromJson('{ "linux/amd64":"linux/amd64","linux/arm64":"linux/arm64/v8" }')[inputs.arch] }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
